const questions = {
    "P1 Viticulture": [
        'Describe how the choice of rootstock can affect viticultural decisions. (2016)',
        'How does site climate influence canopy management decisions? (2022)',
        'Compare the advantages and disadvantages of hand harvesting and machine harvesting. (2017)',
        'Discuss the use and management of cover crops in sustainable viticulture. (2018)',
        'Evaluate different methods of frost protection and their suitability in different vineyard conditions. (2015)',
        'Explain how water availability influences viticultural practices. (2021)',
        'What factors influence the decision to use irrigation in vineyards? (2019)',
        'How do vine training systems impact fruit quality? (2020)',
        'What are the main risks associated with soil erosion in vineyards? (2021)',
        'Discuss the role of organic viticulture in sustainable wine production. (2019)',
        'How does soil type impact vine growth and wine quality? (2018)',
        'Explain the impact of canopy management on the quality of grapevines. (2017)',
        'How do climatic conditions influence harvest timing? (2015)',
        'What are the implications of terroir on wine production? (2020)',
        'Evaluate the use of technology in modern vineyard management. (2021)',
        'How can vineyard pests and diseases be controlled effectively? (2018)',
        'What are the primary environmental factors affecting grapevine health? (2022)',
        'Discuss the different approaches to soil fertility management in vineyards. (2020)',
        'How can growers mitigate the impact of climate change on vineyard productivity? (2019)',
        'What is the role of biodiversity in vineyard health? (2021)',
        'How does canopy density influence fruit set and grape quality? (2019)',
        'Discuss the use of precision viticulture in managing vineyards. (2020)',
        'What are the challenges of managing water stress in vineyards? (2022)',
        'How does the orientation of vineyard rows influence sun exposure and grape ripening? (2017)',
        'What are the different approaches to pruning in viticulture? (2021)',
        'How does the choice of grape variety impact the wine style? (2021)',
        'What are the benefits and risks of converting conventional vineyards to organic viticulture? (2018)',
        'Explain the role of cover crops in maintaining soil health. (2020)',
        'How do vineyard management practices influence the sustainability of wine production? (2019)',
        'What are the risks and benefits of using biodynamic viticulture? (2016)',
        'How do rootstocks affect the resistance of grapevines to diseases and pests? (2022)',
        'Discuss the implications of changing weather patterns for vineyard management. (2017)',
        'What is the role of UV radiation in grapevine growth and fruit composition? (2021)',
        'Evaluate the use of mechanical harvesting in terms of efficiency and grape quality. (2021)',
        'How does the choice of vineyard site affect the wine’s flavor profile? (2020)',
        'What are the effects of vine age on grape yield and quality? (2019)',
        'Explain how vineyard spacing affects vine competition and grape quality. (2018)',
        'Discuss the challenges of managing diseases in a warm climate region. (2022)',
        'How does the altitude of a vineyard influence grape ripening and wine quality? (2020)',
        'What are the most common challenges in managing vineyards in dry climates? (2021)',
        'How does soil management affect the overall productivity of a vineyard? (2021)',
        'What impact do pests like phylloxera have on viticulture? (2015)',
        'Evaluate the importance of maintaining biodiversity in vineyards for pest control. (2022)',
        'What are the latest advancements in vineyard automation? (2021)',
        'How does vineyard orientation impact wind protection and temperature regulation? (2020)',
        'Explain the role of vineyard slope in water drainage and root development. (2017)',
        'What factors contribute to successful grafting in vineyards? (2021)',
        'How do changes in soil pH affect grapevine growth and wine flavor? (2019)',
        'What strategies can be used to manage soil salinity in vineyards? (2022)',
        'How does vineyard diversification contribute to risk management in viticulture? (2018)',
        'Explain the importance of pest monitoring and its impact on crop protection. (2016)'
    ],
    "P2 Vinification": [
        'How does fermentation temperature affect the aromatic profile of white wines? (2019)',
        'Discuss the use of cultured versus ambient yeast in red winemaking. (2016)',
        'Evaluate the advantages of whole bunch fermentation in Pinot Noir production. (2021)',
        'What are the risks and benefits of extended skin contact in white wine production? (2020)',
        'Explain the role of malolactic fermentation in winemaking and its control. (2018)',
        'How does the choice of fermentation vessel impact the wine style? (2020)',
        'What is the importance of lees stirring in the production of white wines? (2017)',
        'How can oxygen management during fermentation influence wine quality? (2019)',
        'Discuss the use of sulphur dioxide in the production of wine. (2017)',
        'What are the different methods of temperature control in fermentation? (2021)',
        'How does the winemaker manage tannin extraction during fermentation? (2021)',
        'What are the effects of oak aging on the flavor profile of wine? (2018)',
        'How does the size of fermentation vessels impact wine style? (2016)',
        'Discuss the advantages and challenges of using amphorae in winemaking. (2020)',
        'What role does acidification play in winemaking? (2019)',
        'Explain the process of pressing in winemaking and its influence on wine style. (2017)',
        'How do different fining agents influence wine clarity and stability? (2020)',
        'What is the role of cold stabilization in wine production? (2018)',
        'How does the pH of the must impact fermentation and wine quality? (2019)',
        'Discuss the use of enzymes in winemaking. (2021)',
        'Explain the role of filtration in wine clarity and stability. (2020)',
        'How does the choice of yeast strain influence the flavor profile of the wine? (2019)',
        'What is the role of maturation in wine production? (2018)',
        'How can the extraction of color and tannins be controlled during fermentation? (2020)',
        'What is the impact of carbonic maceration on red wine style? (2020)',
        'Explain the importance of malolactic fermentation for red wines. (2021)',
        'What is the role of terroir in shaping the fermentation process? (2019)',
        'How can oxidation during fermentation impact wine quality? (2017)',
        'What is the effect of maceration on tannin structure in red wines? (2021)',
        'How do winemakers decide between spontaneous and inoculated fermentation? (2020)',
        'What are the challenges of fermenting high-alcohol wines? (2019)',
        'How does the choice of grape variety impact fermentation techniques? (2018)',
        'Discuss the importance of hygiene in the winemaking process. (2020)',
        'What is the role of pectinase in winemaking? (2016)',
        'How does the temperature during fermentation impact the final wine style? (2021)',
        'Discuss the use of natural wines in the modern winemaking landscape. (2020)',
        'How do winemakers use airlocks during fermentation? (2017)',
        'What are the different techniques used to clarify wine? (2021)',
        'How does fermentation under pressure influence the wine’s texture? (2020)',
        'Explain the impact of fermentation vessels made from different materials on the final product. (2021)',
        'How do wine spoilage organisms affect fermentation? (2020)',
        'What is the importance of post-fermentation maceration for red wines? (2017)',
        'How does fermentation impact the sensory characteristics of wine? (2019)',
        'What are the advantages and disadvantages of cold fermentation? (2021)',
        'Explain the role of controlled fermentation in preserving fresh fruit flavors. (2020)',
        'What is the significance of fermentation kinetics in wine production? (2017)',
        'How does fermentation time impact wine structure and mouthfeel? (2020)',
        'What are the effects of micro-oxygenation in winemaking? (2021)',
        'How does the addition of sugar before fermentation impact wine style? (2020)',
        'What are the key stages in fermentation that influence the final wine profile? (2021)'
    ],
    "P3 Handling of Wine": [
        'Compare the uses of different fining agents and their impact on wine quality. (2017)',
        'Discuss the options available to reduce SO2 in winemaking and their limitations. (2020)',
        'What quality control measures can be used during bottling? (2019)',
        'Explain the advantages and disadvantages of different closure types. (2021)',
        'Evaluate the effect of storage and transportation on wine quality. (2016)',
        'What are the impacts of temperature fluctuation during storage on wine stability? (2021)',
        'How does bottle aging influence wine flavor? (2019)',
        'What are the best practices for managing cork taint in wine? (2020)',
        'How does oxygen management after fermentation influence wine maturation? (2021)',
        'Discuss the importance of cleanliness and hygiene during bottling. (2020)',
        'Explain the role of fining agents in stabilizing wine. (2018)',
        'What are the primary methods of wine stabilization? (2021)',
        'How do storage conditions impact the aging potential of wine? (2021)',
        'How does light exposure affect wine quality? (2020)',
        'What is the significance of bottle shape in wine storage? (2021)',
        'How do wine packaging materials impact the environmental footprint of the industry? (2022)',
        'Discuss the use of refrigeration in wine storage. (2021)',
        'What are the effects of screw cap closures on wine aging? (2020)',
        'What quality control measures are necessary in a bottling line? (2019)',
        'How does the quality of bottles affect wine preservation? (2017)',
        'Explain the importance of monitoring bottle neck oxygen in wine storage. (2021)',
        'What are the challenges of storing wine in humid climates? (2020)',
        'How does the use of inert gases during bottling preserve wine quality? (2019)',
        'How does filtration impact the final wine clarity and stability? (2021)',
        'What are the differences between corks and screw caps in terms of oxygen permeability? (2018)',
        'How does the use of sulfites prevent spoilage and oxidation in wine? (2017)',
        'What are the different methods of preserving wine freshness post-bottling? (2021)',
        'How can you assess the aging potential of wine? (2020)',
        'Discuss the impact of packaging design on wine marketing and consumer perception. (2022)',
        'How can the packaging of wine impact the environment? (2021)',
        'What are the steps involved in handling wine prior to bottling to ensure quality? (2019)',
        'What is the importance of proper storage and transportation logistics for wine? (2020)',
        'Explain the role of wine analysts in maintaining wine quality. (2019)',
        'How does wine chemistry change during the aging process? (2021)',
        'What is the role of fining agents in clarifying wine? (2020)',
        'How do different closure types affect wine aging and preservation? (2017)',
        'What are the best practices for wine labeling and packaging? (2021)',
        'How does refrigeration impact the final flavor of wine? (2019)',
        'What are the best practices for long-term wine storage? (2018)',
        'How does the packaging and transportation of wine impact its marketability? (2021)',
        'What are the challenges of shipping wine internationally? (2020)',
        'What methods can be used to reduce oxidation in wine packaging? (2021)',
        'How does the use of carbon dioxide in storage influence wine preservation? (2017)',
        'What role does temperature control play in maintaining wine quality after bottling? (2020)',
        'What are the best practices for managing wine spoilage during bottling? (2021)',
        'Explain the role of air-tight packaging in preventing wine oxidation. (2020)',
        'How do winemakers assess the impact of storage conditions on wine maturation? (2021)'
    ],
    "P4 Wine Business": [
        'What have been the most important changes in global wine supply and demand in the past years and what are their implications? (2018)',
        'How can the role of intermediaries between producer and consumer be justified? (2017)',
        'What matters more to consumers in today’s wine market: brand, varietal or appellation? (2018 S1)',
        'How important are environmental credentials in marketing wine? (2023 S1)',
        'What are the commercial advantages and disadvantages of packing/bottling wine in the local market of consumption? (2016)',
        'Discuss the impact of e-commerce on the global wine market. (2020)',
        'What is the role of wine tourism in increasing brand awareness? (2021)',
        'How can small wineries differentiate themselves in a competitive market? (2019)',
        'What are the financial challenges facing emerging wine regions? (2021)',
        'How does the global market for organic wine compare to conventional wine? (2020)',
        'What are the primary factors driving wine consumption trends globally? (2020)',
        'Discuss the role of climate change in the global wine market. (2021)',
        'What strategies do producers use to enter international markets? (2021)',
        'How does branding impact consumer perception and choice in the wine industry? (2020)',
        'How can wine brands effectively target younger consumers? (2021)',
        'What are the challenges of marketing fine wines? (2020)',
        'What impact does sustainability have on wine pricing? (2021)',
        'How has the rise of wine apps and social media affected wine sales? (2021)',
        'What are the financial benefits of vertically integrated wine businesses? (2020)',
        'What factors influence wine pricing on the global market? (2020)',
        'What are the implications of changing global import/export regulations for the wine trade? (2021)',
        'How can wine businesses build strong relationships with distributors? (2019)',
        'What role does wine labeling and certification play in international trade? (2020)',
        'How do economic trends influence wine production and distribution? (2018)',
        'How can sustainability in wine production benefit a brand? (2021)',
        'What challenges do wine producers face with online sales and delivery logistics? (2020)',
        'How does the wine trade structure influence market prices? (2019)',
        'What are the advantages and disadvantages of direct-to-consumer wine sales? (2020)',
        'How can wine producers use market research to refine their strategies? (2020)',
        'What role does the wine auction market play in the fine wine sector? (2021)',
        'What are the most important factors to consider in the pricing of wine? (2021)',
        'How do distribution channels influence the marketing and sale of wine? (2020)',
        'What role does sustainability play in shaping consumer buying decisions? (2020)',
        'How can wine businesses attract consumers through brand loyalty programs? (2021)',
        'What factors influence wine retail pricing in different markets? (2019)',
        'How do global wine trade policies affect regional wine production? (2020)',
        'What strategies should wineries implement to reach global consumers effectively? (2021)',
        'How does wine packaging influence its perceived value? (2020)',
        'What are the most successful strategies for increasing wine export sales? (2020)',
        'How has the growth of natural wines impacted the global wine business? (2021)',
        'What are the challenges in creating a brand identity for a new wine label? (2020)',
        'What impact does wine education have on consumer behavior? (2021)',
        'How has wine production been affected by the COVID-19 pandemic in terms of global supply and demand? (2020)',
        'What strategies can wine businesses use to protect their intellectual property? (2021)',
        'How can wine tourism be effectively marketed to increase sales and brand awareness? (2020)'
    ]
};

function getRandomQuestion(category) {
    let selectedQuestions = [];
    if (category === "All Categories") {
        for (let key in questions) {
            selectedQuestions = selectedQuestions.concat(questions[key]);
        }
    } else {
        selectedQuestions = questions[category];
    }
    const randomIndex = Math.floor(Math.random() * selectedQuestions.length);
    return selectedQuestions[randomIndex];
}

function displayQuestion() {
    const category = document.getElementById("category").value;
    const question = getRandomQuestion(category);
    document.getElementById("questionDisplay").innerText = question;
}

function searchQuestions() {
    const searchTerm = document.getElementById("search").value.toLowerCase();
    const results = [];
    for (let key in questions) {
        results.push(...questions[key].filter(q => q.toLowerCase().includes(searchTerm)));
    }
    document.getElementById("questionDisplay").innerText = results.join('\n\n') || "No results found.";
}

function resetDisplay() {
    document.getElementById("search").value = "";
    document.getElementById("questionDisplay").innerText = "";
}
